sudo : required
services:
  - docker

before_install:
  - docker build -t ei5688/client-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true ei5688/client-test npm test -- --coverage


after_success:
  - docker build -t ei5688/multi-client ./client
  - docker build -t ei5688/multi-nginx ./ngnix
  - docker build -t ei5688/multi-server ./server
  - docker build -t ei5688/multi-worker ./worker
  #LOGIN TO DOCKER 
  - echo "$DOCK_PASSWORD" | docker login -u "$DOCK_ID" --password-stdin
  - docker push ei5688/multi-client
  - docker push ei5688/multi-nginx
  - docker push ei5688/multi-server
  - docker push ei5688/multi-worker
