version: "3"
services:
  client:
    image: "ei5688/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "ei5688/multi-server"
    mem_limit: 128m
    hostname: serve
    environment:
      - REDIS_HOST= red-docker.ocorjn.0001.use2.cache.amazonaws.com
      - REDIS_PORT= 6379
      - PGUSER= postgres
      - PGHOST= database-1.cdlafyhvyffb.us-east-2.rds.amazonaws.com
      - PGDATABASE= fibvalue
      - PGPASSWORD= post123456
      - PGPORT=5432
  worker:
    image: "ei5688/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "ei5688/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"